pipeline {
    agent any

     stages {
        stage('Build') {
            steps {
                sh 'docker build -t amirmohammadi60/backend-test1:v-1-${BUILD_NUMBER} .'
            }
        }
        stage('Push to Docker Registry') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'backend-test1', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                    sh 'docker login -u $USERNAME -p $PASSWORD'
                    sh 'docker push amirmohammadi60/backend-test1:v-1-${BUILD_NUMBER} .'
                }
             
             }
        }
        stage('Deploy') {
            steps {
                  
                sh '''
                docker stop backend-test1 || true 
                docker rm -f backend-test1 || true 
                docker run -d -p 8080:80 --name backend-test amirmohammadi60/backend-test1:v-1-${BUILD_NUMBER}.'
                '''
                 
            }
        }
    }
}

